ITSupportingWebApp/ITSupportingWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from elearning.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('about',about, name='about'),
    path('account/',include('account.urls')),
    path('forum/',include('forum.urls')),
    path('elearning/',include('elearning.urls')),
    path('event/',include('event.urls')),
    path('froala/',include('froala_editor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITSupportingWebApp/event/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    path('',views.event_list,name='event_list'),
    path('create_event/',views.create_event,name='create_event'),
    path('<int:pk>/',views.event_detail,name='event_detail'),
    path('<int:pk>/edit',views.edit_event,name='edit_event'),
    path('<int:pk>/delete',views.delete_event,name='delete_event'),
    path('<int:pk>/join',views.join_event,name='join_event'),
    path('notis/',views.notis_json, name='notis.json'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

ITSupportingWebApp/event/models.py
from djongo import models
from django.contrib.auth.models import User
from elearning.models import Course
from froala_editor.fields import FroalaField
from django.dispatch import receiver
from django.db.models.signals import m2m_changed

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=250)
    content = FroalaField()
    ondate = models.DateField(blank=True, null=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events')
    join = models.BooleanField(default=False)
    attendee = models.ManyToManyField(User, related_name='attend_events',blank=True)

    def __str__(self):
        return self.title

class Notification(models.Model):
    receiver = models.ManyToManyField(User, through='Noti_Receiver')
    content = models.TextField(blank=True, null=True)
    link = models.URLField(max_length=1000,blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created'] 

class Noti_Receiver(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='noti_receiver')
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE, related_name='noti_receiver')
    is_read = models.BooleanField(default=False)

ITSupportingWebApp/event/forms.py
from .models import Event
from django.forms import ModelForm
from django import forms
from account.widgets import DateTimePickerInput, TimePickerInput, DatePickerInput

class CreateEventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title','content','join','ondate','start_time','end_time']
    def __init__(self, *args, **kwargs):
        super(CreateEventForm, self).__init__(*args, **kwargs)
        self.fields['ondate'] = forms.DateField(input_formats=['%d/%m/%Y'],widget=DatePickerInput(),required=False)
        self.fields['start_time'] = forms.TimeField(input_formats=['%I:%M %p'],widget=TimePickerInput(),required=False)
        self.fields['end_time'] = forms.TimeField(input_formats=['%I:%M %p'],widget=TimePickerInput(),required=False)

ITSupportingWebApp/event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event, Noti_Receiver, Notification
from .forms import CreateEventForm
from django.http import JsonResponse
import json
from django.utils import timezone
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import serializers
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.
@login_required
def create_event(request):
    if request.user.is_staff or request.user.is_superuser:
        events = Event.objects.all().order_by('-created')
        if request.method == 'POST':
            form = CreateEventForm(request.POST)
            if form.is_valid():
                new_event = form.save(commit=False)
                new_event.created_by = request.user
                new_event.save()
                return redirect('home')
        else:
            form = CreateEventForm()
        return render(request,'event/create_event.html',{'form':form,
                                                        'events':events,})
    else:
        return redirect('home')

def event_list(request):
    search = request.GET.get('search')
    all_events = Event.objects.all().order_by('-created')
    paginator = Paginator(all_events, 10)

    if search != "" and search != None:
        search_events = Event.objects.filter(title__icontains=search) or Event.objects.filter(content__icontains=search)
        search_events = search_events.order_by('-created')
        paginator = Paginator(search_events, 10)
    
    page = request.GET.get('page')
    events = paginator.get_page(page)
    return render(request,'event/event_list.html',{'all_events':all_events,
                                            'events':events, 
                                            'section':'event_list'})

def event_detail(request,pk):
    form = CreateEventForm()
    events = Event.objects.all().order_by('-created')
    event = get_object_or_404(Event, pk=pk)
    user_joined = False
    if request.user.is_authenticated:
        if event in request.user.attend_events.all():
            user_joined = True
    return render(request,'event/event_detail.html',{'form':form,
                                                    'events':events,
                                                    'event':event,
                                                    'user_joined':user_joined})

@login_required
def edit_event(request,pk):
    if request.user.is_staff or request.user.is_superuser:
        events = Event.objects.all().order_by('-created')
        event = get_object_or_404(Event, pk=pk)
        section = 'edit'
        if request.method == 'POST':
            form = CreateEventForm(request.POST,instance=event)
            if form.is_valid():
                form.save()
            return redirect('event_detail',pk)
        else:
            form = CreateEventForm(instance=event)
        return render(request,'event/create_event.html',{'events':events,
                                                        'event':event,
                                                        'section':section,
                                                        'form':form})
    else:
        return redirect('home')

@login_required
def delete_event(request,pk):
    if request.user.is_staff or request.user.is_superuser:
        event = get_object_or_404(Event, pk=pk)
        event.delete()
    return redirect('home')

@login_required
def join_event(request,pk):
    data = {} 
    event = get_object_or_404(Event, pk=pk)
    if request.is_ajax():
        if request.method == 'POST':
            if not request.user.attend_events.filter(pk=pk):
                event.attendee.add(request.user)
            data = {
                'join':"True",
            }
        if request.method == 'DELETE':
            if request.user.attend_events.filter(pk=pk):
                event.attendee.remove(request.user)
            data = {
                'join':"False",
            }
    return JsonResponse(data)

@api_view(['GET','POST'])
def notis_json(request):
    user = request.user
    data = []
    notis = Notification.objects.filter(receiver=user)
    for noti in notis:
        t = timezone.localtime(noti.created)
        data.append({
            'content': noti.content,
            'link' : noti.link,
            'created' : t.strftime('%H:%M %a %d/%m/%y'),
            'is_read' : noti.noti_receiver.get(receiver=user).is_read,
        })
    if request.method == 'GET':
        return Response(data)
    elif request.method == 'POST':
        for noti in notis:
            read = noti.noti_receiver.get(receiver=user)
            read.is_read = True
            read.save()
        return Response(data)

ITSupportingWebApp/event/templates/event/create_event.html
{% extends "forum/base.html" %}

{% load static %}

{% block title %}
    {% if section == 'edit' %}Edit {% else %}Create {% endif %}Event
{% endblock  %}

{% block home %}
    <div class="hero-area section">

			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url({% static 'account/assets/img/background.jpg' %})"></div>
			<!-- /Backgound Image -->
			{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="{% url 'home' %}">Home</a></li>
							<li><a href="{% url 'event_list' %}">Event</a></li>
						</ul>
						<h1 class="white-text">Event Page</h1>
					</div>
				</div>
			</div>
			{% endblock %}
	</div>
{% endblock %}

{% block post %}
    <h1>{% if section == 'edit' %}Edit {% else %}Create new {% endif %} event</h1>
    <form {% if section == 'edit' %} action="{% url 'edit_event' event.pk %}" {% else %} action="{% url 'create_event' %}" {% endif %} method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="main-button icon-button">Post</button>
    </form>
    <script>
        function check(){
            var join = $('#id_join').is(':checked');
            if (join == false){
                $("#id_ondate").prop('disabled', true);
                $("#id_start_time").prop('disabled', true);
                $("#id_end_time").prop('disabled', true);
            }
            else{
                $("#id_ondate").prop('disabled', false);
                $("#id_start_time").prop('disabled', false);
                $("#id_end_time").prop('disabled', false);
            }
        }

        check();

        $('#id_join').on('click',function(){
            check();
        });
    </script>
{% endblock %}

{% block aside %}
    <!-- aside blog -->
    <div id="aside" class="col-md-3">

        <!-- search widget -->
        <div class="widget search-widget">
            <form method="GET" action="{% url 'event_list' %}">
                <input class="input" type="text" name="search" placeholder="Search Events">
                <button><i class="fa fa-search"></i></button>
            </form>
        </div>
        <!-- /search widget -->

        <!-- posts widget -->
        <div class="widget posts-widget">
            <h3>Latest Events</h3>
            {% for e in events %}
            {% if forloop.counter <= 3 %}
            <!-- single posts -->
            <div class="single-post">
                {% comment %} <a class="single-post-img" href="#">
                    <img src="{% static 'img/blog01.jpg' %}" alt="">
                </a> {% endcomment %}
                <a href="#">{{ e.title }}</a>
                <p><small>By {{e.created_by}}. {{e.created}}</small></p>
            </div>
            <!-- /single posts -->
            {% endif %}
            {% empty %}
            <p>There is no event</p>
            {% endfor %}

        </div>
        <!-- /posts widget -->

    </div>
    <!-- /aside blog -->
{% endblock %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/event/templates/event/event_detail.html
{% extends "forum/base.html" %}

{% load static %}

{% load widget_tweaks %}

{% block title %}
    {{ event.title }}
{% endblock %}

{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="{% url 'home' %}">Home</a></li>
							<li><a href="{% url 'event_list' %}">Events</a></li>
							<li><a href="{% url 'event_detail' event.pk %}">{{ event.title }}</a></li>
						</ul>
						<h1 class="white-text">{{event.title}}</h1>
                        <ul class="blog-post-meta">
							<li class="blog-meta-author">By : <a href="#">{{event.created_by}}</a></li>
							<li>{{event.created}}</li>
						</ul>
					</div>
				</div>
			</div>
{% endblock %}

{% block post %}
	<!-- blog post -->
	<div class="blog-post fr-view">
		{% autoescape off %}
            {{ event.content }}
        {% endautoescape %}
	</div>
	<div class="row">
        {% if event.join == True %}
		<span class="pull-left">
			<button id="join" class="btn btn-success"><i class="fas fa-user-plus">{% if request.user.is_authenticated %} Click to Join{% else %} Login to Join{% endif %}</i></button>
		</span>
        {% endif %}
        {% if request.user.is_staff or request.user.is_superuser %}
		<span class="pull-right">
			<a href="{% url 'edit_event' event.pk %}"><button class="btn btn-success"><i class="fas fa-edit"></i></button></a>
			<a href="{% url 'delete_event' event.pk %}"><button class="btn btn-success"><i class="fas fa-trash-alt"></i></button></a>
		</span>
        {% endif %}
	</div>
    <hr>
	<script>
        var user_joined = "{{ user_joined }}";

        if(user_joined.localeCompare("True")==0){
            $("#join i").replaceWith("Cancel");
            method = "DELETE";
        }

        $("#join").on("click",function(){
            var method = "POST";

            if(user_joined.localeCompare("True")==0){
                method = "DELETE";
            }

            $.ajax({
                method: method,
                url: "{% url 'join_event' event.pk %}",
                headers: {'X-CSRFToken':'{{csrf_token}}'},
                success: function(data){
                    user_joined = data['join'];
                }
            })
            
            if(method.localeCompare("POST")==0){
                $("#join i").replaceWith("<i class='fas fa-user-minus'> Cancel</i>");
            }
            else{
                $("#join i").replaceWith("<i class='fas fa-user-plus'> Click to Join</i>");
            }
        })
	</script>
	<!-- /blog post -->
{% endblock %}

{% block aside %}
    <!-- aside blog -->
    <div id="aside" class="col-md-3">

        <!-- search widget -->
        <div class="widget search-widget">
            <form method="GET" action="{% url 'event_list' %}">
                <input class="input" type="text" name="search" placeholder="Search Events">
                <button><i class="fa fa-search"></i></button>
            </form>
        </div>
        <!-- /search widget -->

        <!-- posts widget -->
        <div class="widget posts-widget">
            <h3>Latest Events</h3>
            {% for e in events %}
            {% if forloop.counter <= 3 %}
            <!-- single posts -->
            <div class="single-post">
                {% comment %} <a class="single-post-img" href="#">
                    <img src="{% static 'img/blog01.jpg' %}" alt="">
                </a> {% endcomment %}
                <a href="#">{{ e.title }}</a>
                <p><small>By {{e.created_by}}. {{e.created}}</small></p>
            </div>
            <!-- /single posts -->
            {% endif %}
            {% empty %}
            <p>There is no event</p>
            {% endfor %}

        </div>
        <!-- /posts widget -->

    </div>
    <!-- /aside blog -->
{% endblock %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/event/templates/event/event_list.html
{% extends "forum/base.html" %}

{% block title %}
    Event List
{% endblock %}

{% block home-wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1 text-center">
				<ul class="hero-area-tree">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'event_list' %}">Events</a></li>
                </ul>
                <h1 class="white-text">Events</h1>
            </div>
        </div>
    </div>
{% endblock %}

{% block post %}
    <h2>All Events</h2>
    <hr>
    {% for event in events %}
    <div class="feature">
        <div class="feature-content" style="padding-left:0px;">
            <h4><a href="{% url 'event_detail' event.pk %}">{{ event.title }}</a></h4>
            <p>{{ event.content|safe|truncatewords_html:30 }}</p>
            <p>{{event.created_by}}, <span class="date">{{ event.created }}</span></p>
        </div>
    </div>
    <hr>
    {% empty %}
    There is no event match.
    {% endfor %}
{% endblock %}

{% block aside %}
<!-- aside blog -->
<div id="aside" class="col-md-3">

    <!-- search widget -->
    <div class="widget search-widget">
        <form method="GET">
            <input class="input" type="text" name="search" placeholder="Search Events">
            <button><i class="fa fa-search"></i></button>
        </form>
    </div>
    <!-- /search widget -->

    <!-- posts widget -->
    <div class="widget posts-widget">
        <h3>Latest Events</h3>
        {% for e in all_events %}
        {% if forloop.counter <= 3 %}
        <!-- single posts -->
        <div class="single-post">
            {% comment %} <a class="single-post-img" href="#">
                <img src="{% static 'img/blog01.jpg' %}" alt="">
            </a> {% endcomment %}
            <a href="#">{{ e.title }}</a>
            <p><small>By {{e.created_by}}. {{e.created}}</small></p>
        </div>
        <!-- /single posts -->
        {% endif %}
        {% empty %}
        <p>There is no event</p>
        {% endfor %}

    </div>
    <!-- /posts widget -->

</div>
<!-- /aside blog -->
{% endblock %}

{% block paging %}
<div class="col-md-12">
    <div class="post-pagination">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ events.previous_page_number }}" class="pagination-back pull-left">previous</a>
        {% endif %}

        <ul class="pages">
            {% for i in events.paginator.page_range %}
                {% if events.number == i %}
                    <li class="active">{{ i }}</li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
        </ul>

        {% if events.has_next %}
            <a href="?page={{ events.next_page_number }}" class="pagination-next pull-right">next</a>
            <a href="?page={{ events.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </div>
</div>
{% endblock %}