ITSupportingWebApp/ITSupportingWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from elearning.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('about',about, name='about'),
    path('account/',include('account.urls')),
    path('forum/',include('forum.urls')),
    path('elearning/',include('elearning.urls')),
    path('event/',include('event.urls')),
    path('froala/',include('froala_editor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITSupportingWebApp/elearning/urls.py
from django.urls import path,include
from . import views
from rest_framework import routers

app_name = 'elearning'

router = routers.DefaultRouter()
router.register(r'majors', views.MajorViewSet)

urlpatterns = [
    path('program/',views.program,name='program'),
    path('course_offerings/<str:pk>/',views.course_offering_detail,name='course_offering_detail'),
    path('course_offerings/<str:pk>/staff_contact',views.owner_contact,name='owner_contact'),
    path('course_offerings/<str:pk>/discussion',views.discussion,name='discussion'),
    path('course_offerings/<str:pk>/add_content',views.add_content,name='add_content'),
    path('course_offerings/<str:pk>/contents/<str:content_pk>',views.content_detail,name='content_detail'),
    path('course_offerings/<str:pk>/contents/<str:content_pk>/edit',views.edit_content,name='edit_content'),
    path('course_offerings/<str:pk>/add_assignment',views.add_assignment,name='add_assignment'),
    path('course_offerings/<str:pk>/assignments',views.assignments,name='assignments'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/',views.assignment_detail,name='assignment_detail'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/submissions',views.submissions_json,name='submissions.json'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/edit',views.edit_assignment,name='edit_assignment'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/delete',views.delete_assignment,name='delete_assignment'),
    path('course_offerings/<str:pk>/grades/',views.grade_list,name='grade_list'),
    path('course_offerings/<str:pk>/grades/<str:username>',views.grade,name='grade'),
    path('majors/<str:major_slug>/',views.course_list,name='course_list'),
    path('courses/<str:pk>/',views.course_detail,name='course_detail'),
    path('enroll/',views.enroll,name='enroll'),
    path('enroll/course_offerings.json',views.course_offerings_json,name='course_offerings.json'),
    path('enroll/enroll.json',views.enroll_json,name='enroll.json'),
    path('', include(router.urls)),
]

ITSupportingWebApp/event/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    path('',views.event_list,name='event_list'),
    path('create_event/',views.create_event,name='create_event'),
    path('<int:pk>/',views.event_detail,name='event_detail'),
    path('<int:pk>/edit',views.edit_event,name='edit_event'),
    path('<int:pk>/delete',views.delete_event,name='delete_event'),
    path('<int:pk>/join',views.join_event,name='join_event'),
    path('notis/',views.notis_json, name='notis.json'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

ITSupportingWebApp/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block css_extra %}
<style>
  .carousel-inner img {
    -webkit-filter: grayscale(90%);
    filter: none; /* make all photos black and white */ 
    width: 100%; /* Set width to 100% */
    max-height: 500px;
    margin: auto;
  }
  .carousel-caption h3 {
    color: #fff !important;
  }
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; /* Hide the carousel text when the screen is less than 600 pixels wide */
    }
  }
  .date {
	font-size:12px;
	color:#374050;
    }
</style>
{% endblock %}

{% block transparent-nav %}

{% endblock %}

{% block home %}
    {% comment %} <!-- Home -->
    <div id="home" class="hero-area">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'account/assets/img/background.jpg' %})">
        </div>
        <!-- /Backgound Image -->

        <div class="home-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h1 class="white-text">Welcome to School of Computer Science and Engineering</h1>
                        <p class="lead white-text">Libris vivendo eloquentiam ex ius, nec id splendide abhorreant, eu pro alii error homero.</p>
                        <a class="main-button icon-button" href="#">Get Started!</a>
                    </div>
                </div>
            </div>
        </div> 

    </div>
    <!-- /Home --> {% endcomment %}
{% endblock %}

{% block content %}
    <!-- Test carousel -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
        {% for img in bg_images %}
            <li data-target="#myCarousel" data-slide-to="{{ forloop.counter|add:'-1' }}" class="active"></li>
        {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for img in bg_images %}
            <div class="item {% if forloop.counter == 1 %} active {% endif %}">
                <img src="{{ img.url }}" alt="Internation University" width="1200" height="700">
                <div class="carousel-caption">
                    <h3>International University</h3>
                </div>      
            </div>
            {% endfor %}
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!-- /Test carousel-->

    <!-- Events -->
    <div id="events" class="section">

        <!-- container -->
        <div class="container">

            <!-- row -->
            <div class="row">

                <div class="col-md-6">
                    <div class="section-header">
                        <h2>Welcome to School of Computer Science and Engineering</h2>
                        <img src="{% static 'img/introduction.jpeg' %}" alt="introduction" style="padding:20px; width:500px; height:auto;">
                        <p style="padding-left:20px;">In facing the rapid development of Information Technology, school of Computer Science and Engineering of International University (IU) offers intensive programs with a goal to train IT staffs to meet the current industry’s demand.</p>
                    </div>
                </div>

                <div class="col-md-6">
                    <h3>Latest News
                        {% if request.user.is_staff or request.user.is_superuser %}
                        <span>
                            <a href="{% url 'create_event' %}"><i class="btn btn-success pull-right fas fa-plus-circle"></i></a>
                        </span>
                        {% endif %}
                    </h3>
                    <hr>
                    <!-- feature -->
                    {% for event in events %}
                        {% if forloop.counter <= 5 %}
                            {% if forloop.counter != 1 %}
                            <hr>
                            {% endif %}
                        <div class="feature">
                            <div class="feature-content" style="padding-left:0px;">
                                <h4><a href="{% url 'event_detail' event.pk %}">{{ event.title }}</a></h4>
                                <p>{{ event.content|safe|truncatewords_html:30 }}</p>
                                <p>{{event.created_by}}, <span class="date">{{ event.created }}</span></p>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                    <!-- /feature -->
                    <a href="{% url 'event_list' %}"><button class="btn btn-link pull-right">Read more</button></a>
                </div>

            </div>
            <!-- row -->

        </div>
        <!-- container -->
    </div>
    <!-- /Events -->

    <!-- Call To Action -->
    <div id="cta" class="section">

        <!-- Backgound Image -->
        <div class="bg-image bg-parallax overlay" style="background-image:url({% static 'img/enroll-1.png' %})"></div>
        <!-- /Backgound Image -->

        <!-- container -->
        <div class="container">

            <!-- row -->
            <div class="row">

                <div class="col-md-6">
                    <h2 class="white-text">Join our programs</h2>
                    <p class="lead white-text">Ceteros fuisset mei no, soleat epicurei adipiscing ne vis. Et his suas veniam nominati.</p>
                    <a class="main-button icon-button" href="{% url 'elearning:enroll' %}">Enroll</a>
                </div>

            </div>
            <!-- /row -->

        </div>
        <!-- /container -->

    </div>
    <!-- /Call To Action -->

    <!-- Majors -->
    <div id="majors" class="section">

        <!-- container -->
        <div class="container">

            <!-- row -->
            <div class="row">
                <div class="section-header text-center">
                    <h2>Our Majors</h2>
                    <p class="lead">Our Department includes {% with majors.count as num_majors %}{{ num_majors }}{% endwith %} majors:</p>
                </div>

                {% for major in majors %}
                <!-- feature -->
                <div class="col-md-4">
                    <div class="feature">
                        <i class="feature-icon fa fa-university"></i>
                        <div class="feature-content">
                            <h4><a href="{% url 'elearning:course_list' major.slug %}">{{ major.name }}</a></h4>
                            <p>{{ major.content }}</p>
                        </div>
                    </div>
                </div>
                <!-- /feature -->
                {% endfor %}

            </div>
            <!-- /row -->

            <hr class="section-hr" style="margin-bottom:0px">
        
            <!-- Courses -->
            <div id="courses" class="section">

                <!-- container -->
                <div class="container">

                    <!-- row -->
                    <div class="row">
                        <div class="section-header text-center">
                            <h2>Explore Courses</h2>
                            <p class="lead">Our Department includes {% with courses.count as num_courses %}{{ num_courses }}{% endwith %} courses:</p>
                        </div>
                    </div>
                    <!-- /row -->

                    <!-- courses -->
                    <div id="courses-wrapper">

                        <!-- row -->
                        {% for course in courses %}
                        {% if forloop.counter <= 8 %}
                        
                        {% if forloop.counter == 1 or forloop.counter == 5 %}
                        <div class="row">
                        {% endif %}

                            <!-- single course -->
                            <div class="col-md-3 col-sm-6 col-xs-6">
                                <div class="course">
                                    <a href="{% url 'elearning:course_detail' course.pk %}" class="course-img">
                                        <img src="
                                        {% if course.picture %}
                                        {{ MEDIA_URL }}{{ course.picture }}
                                        {% else %}
                                        {% static 'img/course-default.jpg' %}
                                        {% endif %}" alt="{{ course.title }}" style="height:175px;width=263px;">
                                        <i class="course-link-icon fa fa-link"></i>
                                    </a>
                                    <a class="course-title" href="{% url 'elearning:course_detail' course.pk %}">{{ course.title }}</a>
                                    <div class="course-details">
                                        <span class="course-category">{{ course.category }}</span>
                                        <span class="course-price course-free">{{ course.num_credits }}</span>
                                    </div>
                                </div>
                            </div>
                            <!-- /single course -->

                        {% if forloop.counter == 4 or forloop.counter == 8 %}
                        </div>
                        {% endif %}

                        {% endif %}
                        {% endfor %}
                        <!-- /row -->

                    </div>
                    <!-- /courses -->

                    <div class="row">
                        <div class="center-btn">
                            <a class="main-button icon-button" href="#">More Courses</a>
                        </div>
                    </div>

                </div>
                <!-- container -->

            </div>
            <!-- /Courses -->

        </div>
        <!-- /container -->
        
    </div>
    <!-- /Majors -->
    
{% endblock %}