ITSupportingWebApp/ITSupportingWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from elearning.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('about',about, name='about'),
    path('account/',include('account.urls')),
    path('forum/',include('forum.urls')),
    path('elearning/',include('elearning.urls')),
    path('event/',include('event.urls')),
    path('froala/',include('froala_editor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITSupportingWebApp/elearning/urls.py
from django.urls import path,include
from . import views
from rest_framework import routers

app_name = 'elearning'

router = routers.DefaultRouter()
router.register(r'majors', views.MajorViewSet)

urlpatterns = [
    path('program/',views.program,name='program'),
    path('course_offerings/<str:pk>/',views.course_offering_detail,name='course_offering_detail'),
    path('course_offerings/<str:pk>/staff_contact',views.owner_contact,name='owner_contact'),
    path('course_offerings/<str:pk>/discussion',views.discussion,name='discussion'),
    path('course_offerings/<str:pk>/add_content',views.add_content,name='add_content'),
    path('course_offerings/<str:pk>/contents/<str:content_pk>',views.content_detail,name='content_detail'),
    path('course_offerings/<str:pk>/contents/<str:content_pk>/edit',views.edit_content,name='edit_content'),
    path('course_offerings/<str:pk>/add_assignment',views.add_assignment,name='add_assignment'),
    path('course_offerings/<str:pk>/assignments',views.assignments,name='assignments'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/',views.assignment_detail,name='assignment_detail'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/submissions',views.submissions_json,name='submissions.json'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/edit',views.edit_assignment,name='edit_assignment'),
    path('course_offerings/<str:pk>/assignments/<int:assignment_pk>/delete',views.delete_assignment,name='delete_assignment'),
    path('course_offerings/<str:pk>/grades/',views.grade_list,name='grade_list'),
    path('course_offerings/<str:pk>/grades/<str:username>',views.grade,name='grade'),
    path('majors/<str:major_slug>/',views.course_list,name='course_list'),
    path('courses/<str:pk>/',views.course_detail,name='course_detail'),
    path('enroll/',views.enroll,name='enroll'),
    path('enroll/course_offerings.json',views.course_offerings_json,name='course_offerings.json'),
    path('enroll/enroll.json',views.enroll_json,name='enroll.json'),
    path('', include(router.urls)),
]

ITSupportingWebApp/event/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    path('',views.event_list,name='event_list'),
    path('create_event/',views.create_event,name='create_event'),
    path('<int:pk>/',views.event_detail,name='event_detail'),
    path('<int:pk>/edit',views.edit_event,name='edit_event'),
    path('<int:pk>/delete',views.delete_event,name='delete_event'),
    path('<int:pk>/join',views.join_event,name='join_event'),
    path('notis/',views.notis_json, name='notis.json'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

ITSupportingWebApp/elearning/forms.py
from django import forms
from django.forms import ModelForm
from .models import Course, Course_Offering, Content, Semester, Major, CourseGrade, Assignment, Submission, EnrollDate, Discussion
from django.contrib.auth.models import User
from account.models import Profile
from account.widgets import DateTimePickerInput, TimePickerInput, DatePickerInput
from django.utils.dateformat import DateFormat, TimeFormat

class CourseForm(ModelForm): 
    requirements = forms.ModelMultipleChoiceField(queryset=Course.objects.all(),
                                                widget=forms.CheckboxSelectMultiple(),required=False)
    class Meta:
        model = Course
        fields = ['picture','title','department','required_credits','overview','num_credits','semester','category','major']

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.fields['major'] = forms.ModelMultipleChoiceField(queryset=Major.objects.all(),
                                                widget=forms.CheckboxSelectMultiple(),required=False)
        

class CourseOfferingForm(ModelForm):
    class Meta:
        model = Course_Offering
        fields = ['course','lecturer','num_students','semester','start_date','start_time','end_time']

    def __init__(self, *args, **kwargs):
        super(CourseOfferingForm, self).__init__(*args, **kwargs)
        users = User.objects.filter(is_active=True)
        username = []
        for user in users:
            if user.profile.role == 'professor':
                username.append(user.username)
        users = User.objects.filter(username__in=username)
        self.fields['lecturer'].queryset = users
        self.fields['start_date'] = forms.DateField(input_formats=['%d/%m/%Y'],widget=DatePickerInput())
        self.fields['start_time'] = forms.TimeField(input_formats=['%I:%M %p'],widget=TimePickerInput())
        self.fields['end_time'] = forms.TimeField(input_formats=['%I:%M %p'],widget=TimePickerInput())

class AddContentForm(ModelForm):
    image_field = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    file_field = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Content
        fields = ['title','body']

class CreateSemesterForm(ModelForm):
    class Meta:
        model = Semester
        fields = ['start','end']

    def __init__(self, *args, **kwargs):
        super(CreateSemesterForm, self).__init__(*args, **kwargs)
        self.fields['start'] = forms.DateField(input_formats=['%d/%m/%Y'],widget=DatePickerInput())
        self.fields['end'] = forms.DateField(input_formats=['%d/%m/%Y'],widget=DatePickerInput())

class CreateMajorForm(ModelForm):
    class Meta:
        model = Major
        fields = ['name','content']

class InputGradeForm(ModelForm):
    class Meta:
        model = CourseGrade
        fields = ['assignment','midterm','final']

class CreateAssignment(ModelForm):

    class Meta:
        model = Assignment
        fields = ['title','body','deadline']

    def __init__(self, *args, **kwargs):
        super(CreateAssignment, self).__init__(*args, **kwargs)
        self.fields['deadline'] = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'],widget=DateTimePickerInput())

class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        fields = ['File','body']

class EnrollDateForm(ModelForm):
    class Meta:
        model = EnrollDate
        fields = ['start_enroll','end_enroll']

    def __init__(self, *args, **kwargs):
        super(EnrollDateForm, self).__init__(*args, **kwargs)
        self.fields['start_enroll'] = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'],widget=DateTimePickerInput())
        self.fields['end_enroll'] = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'],widget=DateTimePickerInput())

class DiscussionForm(ModelForm):
    class Meta:
        model = Discussion
        fields = ['message']

ITSupportingWebApp/elearning/views.py
from django.shortcuts import render, redirect, Http404, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from .models import Course, Course_Offering, Content, Content_File, Content_Image, Requirement, Major, Semester, CourseGrade, Assignment, Submission, EnrollDate, Discussion
from .forms import CourseForm, CourseOfferingForm, AddContentForm, CreateSemesterForm, InputGradeForm, CreateAssignment, SubmissionForm, DiscussionForm
from rest_framework import viewsets, serializers
import math
from event.models import Notification, Noti_Receiver, Event
from django.utils import timezone
import json
from django.utils.dateformat import DateFormat, TimeFormat
import os

# Create your views here.

def background_img():
    data = [
        {
            'url': 'static/account/assets/img/background.jpg'
        },
        {
            'url': 'static/img/background-2.jpeg'
        },
        {
            'url': 'static/img/background-3.jpg'
        },
        {
            'url': 'static/img/background-4.jpg',
        },
    ]
    return data

def home(request):
    bg_images = background_img()
    events = Event.objects.all().order_by('-created')
    majors = Major.objects.all()
    courses = Course.published.all()
    return render(request,'home.html',{'majors':majors,
                                    'courses':courses,
                                    'events':events,
                                    'bg_images': bg_images})

def about(request):
    List = ['Dean','Vice Dean']
    majors = Major.objects.all()
    for major in majors:
        List.append(major.name+' Professor')
    groups = Group.objects.filter(name__in=List)
    for group in groups:
        group_users = []
        for user in User.objects.filter(profile__role="professor"):
            if user.groups.filter(name=group.name):
                group_users.append(user)
        group.users = group_users
    return render(request,'elearning/about.html',{'groups':groups})    

def get_user(request):
    user = User.objects.get(username=request.user.username)
    return user

def program(request):
    majors = Major.objects.all()
    courses = Course.published.all()
    return render(request,'elearning/program.html',{'majors':majors,
                                                    'courses':courses})

def get_categories(major):
    courses = Course.objects.filter(major=major)
    credits = {
            'general courses': 0,
            'core courses': 0,
            'major courses': 0,
            'others': 0,
            'total': 0,
        }
    categories = []
    if courses:
        for course in courses:
            credits[course.category] += course.num_credits
            credits['total'] += course.num_credits
        for each in credits:
            if each == 'total':
                continue
            categories.append({
                'name': each,
                'credits': credits[each],
                'percent': str( round((credits[each]/credits['total'])*100,1) ) + '%',
            })
    else:
        for each in credits:
            if each == 'total':
                continue
            categories.append({
                'name': each,
                'credits': credits[each],
                'percent': '0.0%',
            })
    return categories

def get_mycourses(request):
    my_courses = ''
    if request.user.is_authenticated:
        if request.user.profile.role == "student":
            my_courses = request.user.course_grade.all()
        elif request.user.profile.role == "professor":
            my_courses = request.user.teaching_courses.all()
    return my_courses

def course_list(request, major_slug):
    major = Major.objects.get(pk=major_slug)
    categories = get_categories(major)
    courses = Course.objects.filter(major=major)
    semesters = range(1,9)
    my_courses = get_mycourses(request)
    return render(request,'elearning/course_list.html',{'my_courses':my_courses,
                                                    'categories':categories,
                                                    'semesters':semesters,
                                                    'courses':courses,
                                                    'major':major,})

def course_detail(request, pk):
    course = Course.published.get(pk=pk)
    now = timezone.now().date()
    semester = Semester.objects.all().order_by('-start')[0]
    course_offerings = course.course_offerings.filter(status__in=['published','started'],semester=semester)
    return render(request,'elearning/course_detail.html',{'course':course,'course_offerings':course_offerings})

def check_requirement(semester, course_offering, user):
    registered_courses = user.course_grade.filter(semester=semester)

    course_offering.registered = False
    for registered_course in registered_courses:
        if course_offering == registered_course.course_offering:
            course_offering.registered = True

    if (course_offering.course.semester %2 ) == 0:
        course_offering.year = (course_offering.course.semester//2)
    else:
        course_offering.year = (course_offering.course.semester//2)+1

    #check for requirement
    year_now = timezone.now().year
    student_year = year_now - user.entrance_student.latest('pk').year
    if semester.semester == 'semester 1':
        student_year = student_year + 1

    messages = []
    if student_year >= course_offering.year :
        course_offering.qualified = True
        requirements = course_offering.course.following_courses.all()
        
        for requirement in requirements:
            if not user.course_grade.filter(course=requirement.required_course).exclude(semester=semester):
                course_offering.qualified = False
                messages.append(requirement.required_course.title+" (not yet)")
        course_offering.messages = messages
    else:
        course_offering.qualified = False
        messages.append("You are in "+str(student_year)+" year")
        course_offering.messages = messages
    
    course_offering_json = {
        'course_id': course_offering.course.course_id,
        'offering_id': course_offering.pk,
        'course': course_offering.course.title,
        'lecturer': course_offering.lecturer.username,
        'year': course_offering.year,
        'start_date': DateFormat(course_offering.start_date).format('d/m/Y'),
        'day': DateFormat(course_offering.start_date).format('D'),
        'start_time': TimeFormat(course_offering.start_time).format('H:i'),
        'end_time': TimeFormat(course_offering.end_time).format('H:i'),
        'num_students': course_offering.num_students,
        'num_credits': course_offering.course.num_credits,
        'slot': course_offering.slot,
        'qualified': course_offering.qualified,
        'messages': course_offering.messages,
        'registered': course_offering.registered,
    }
    return course_offering_json

def course_offerings_json(request):
    try:
        user = request.user
        semester = Semester.objects.latest('start')
        course_offerings = Course_Offering.objects.filter(status__in=['published'],semester=semester).order_by("course")
        
        if request.is_ajax():
            if request.method == 'POST':
                json_data = request.read()
                data = json.loads(json_data)
                search = data['search']
                if search != "":
                    courses = Course.objects.filter(title__icontains=search)
                    course_offerings = Course_Offering.objects.filter(status='published',semester=semester,course__in=courses) | Course_Offering.objects.filter(status='published',semester=semester,offering_id__icontains=search)
        data = []
        for course_offering in course_offerings:
            course_offering_json = check_requirement(semester, course_offering, user)
            data.append(course_offering_json)
    except:
        print('Something went wrong during search.')
        data=[]
    return JsonResponse(data,safe=False)

def validate_enroll(request, course_offering):
    # check if user is busy or that course is already registered in that semester
    validate = None
    user = request.user
    semester = course_offering.semester
    message = None

    if course_offering.slot > 0:
        if semester.semester == 'semester 3':
            total_credits = 12
        else:
            total_credits = 24

        registered_courses = user.course_grade.filter(semester=semester)
        student_credits = 0

        for each in registered_courses:
            student_credits = student_credits + each.course.num_credits
        
        if( (student_credits + course_offering.course.num_credits) <= total_credits):
            #check if course_offering is already registered or not
            if not registered_courses.filter(course_offering=course_offering):
                #check if course is already registered in that semester
                for each in registered_courses:
                    if course_offering.course == each.course:
                        validate = False
                        message = "You have registered this course in this semester"
                    else:
                        if DateFormat(course_offering.start_date).format('D') == DateFormat(each.course_offering.start_date).format('D'):
                            if course_offering.start_time < each.course_offering.start_time:
                                if course_offering.end_time < each.course_offering.start_time:
                                    validate = True
                                else:
                                    validate = False
                            elif course_offering.start_time > each.course_offering.end_time:
                                validate = True
                            else:

ITSupportingWebApp/elearning/templates/elearning/add_assignment.html
{% extends "elearning/course_offering_detail.html" %}

{% block title %}
    Add Assignment
{% endblock  %}

{% block course %}

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">{% if section == 'edit' %}Edit Assignment{% else %}Add Assignment{% endif %}</div>
            <div class="panel-body">
                <form {% if section == 'edit' %}action="{% url 'elearning:edit_assignment' course_offering.pk assignment.pk %}"{% else %}action="{% url 'elearning:add_assignment' course_offering.pk %}"{% endif %} method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="main-button icon-button">Add</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

ITSupportingWebApp/elearning/templates/elearning/assignments.html
{% extends "elearning/course_offering_detail.html" %}

{% block title %}
    Assignments
{% endblock  %}

{% block course %}

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Assignments</div>
            <div class="panel-body">
                <ul>
                    {% for assignment in assignments %}
                    <li>
                        <h4>{{ assignment.title }}</h4>
                        <p>{{ assignment.body|truncatewords:10|safe }}</p>
                        <p class="date">Updated: {{ assignment.updated|date:'d/m/Y, H:i' }}</p>
                        <span class="date" style="color:red;">Deadline: {{ assignment.deadline|date:'d/m/Y, H:i' }}</span>                        
                        <div class="pull-right">
                        {% if request.user.profile.role == 'professor' %}
                            <a href="{% url 'elearning:edit_assignment' course_offering.pk assignment.pk %}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'elearning:delete_assignment' course_offering.pk assignment.pk %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                            <a href="{% url 'elearning:assignment_detail' course_offering.pk assignment.pk %}" class="btn btn-success">View Submissions</a>
                        {% else %}
                        {% if assignment.is_submitted == True %}
                            <a href="{% url 'elearning:assignment_detail' course_offering.pk assignment.pk %}#submissions" class="btn btn-success">View Submission</a>
                        {% else %}
                            <a href="{% url 'elearning:assignment_detail' course_offering.pk assignment.pk %}#SubmissionForm" class="btn btn-success">Submit</a>
                        {% endif %}
                        {% endif %}
                        </div>
                    </li>
                    <hr>
                    {% empty %}
                    <p>There is no assignment.</p>
                    {% endfor %}
                </ul>
                {% if request.user.profile.role == 'professor' %}
                <div class="pull-right">
                    <a href="{% url 'elearning:add_assignment' course_offering.pk %}" class="btn btn-success">add assignment</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock  %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/elearning/templates/elearning/course_list.html
{% extends "elearning/base.html" %}

{% block title %}
    Course List
{% endblock  %}

{% block css_extra %}
<style>

    #course-aside-panel .list-group-item {
        font-size: 10pt;
    }

    li.borderless {
        border-top: 0 none;
    }

</style>
{% endblock %}

{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="index.html">Home</a></li>
							<li><a href="{% url 'elearning:program' %}">Program</a></li>
						</ul>
						<h1 class="white-text">{{ major.name }}</h1>

					</div>
				</div>
			</div>
{% endblock %}

{% block course %}

    <h3>Distribution of Curriculum</h3>
    <table class="table table-hover">
        <thead>
            <tr class="info">
                <th class="text-left">Courses</th>
                <th class="text-center">Credits</th>
                <th class="text-center">Percent</th>              
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td class="text-left">{{ category.name }}</td>
                <td class="text-center">{{ category.credits }}</td>
                <td class="text-center">{{ category.percent }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <h3>Curriculum</h3>
    
    {% for semester in semesters %}
    {% if forloop.counter == 1 or forloop.counter == 3 or forloop.counter == 5 or forloop.counter == 7  %}
    <div class="row">
    {% endif %}
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#semester{{semester}}">
                    <h4 class="panel-title" style="color:#1f808c;font-size:14px;">
                        Semester {{ semester }}<span class="caret pull-right"></span>
                    </h4>
                </div>
                <div id="semester{{semester}}" class="panel-collapse collapse">
                    <table class="table table-hover">
                        <thead>
                            <tr class="info">
                                <th class="text-left col-md-8">Course</th>
                                <th class="text-center col-md-4">Credits</th>
                                          
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in courses %}
                            {% if course.semester == semester %}
                            <tr>
                                <td class="text-left col-md-8">
                                    <a href="{% url 'elearning:course_detail' course.pk %}">{{ course.title }}</a>
                                </td>
                                <td class="text-center col-md-4">{{ course.num_credits }}</td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>		
            </div>
        </div>
    {% if forloop.counter == 2 or forloop.counter == 4 or forloop.counter == 6 or forloop.counter == 8  %}
    </div>
    {% endif %}
    {% endfor %}

{% endblock  %}

{% block paging %}

{% endblock %}

{% block extra-aside %}
{% if request.user.profile.role == "student" or request.user.profile.role == "professor" %}    
    <div class="widget">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#course-aside-panel">
                    <h4 class="panel-title" style="color:#1f808c;font-size:14px;">My Courses
                        <span class="caret pull-right"></span>  
                    </h4>
                </div>
                <div id="course-aside-panel" class="panel-collapse collapse">
                    <ul class="list-group">
                        {% for course_offering in my_courses %}
                        <li class="list-group-item borderless"><a href="{% url 'elearning:course_offering_detail' course_offering.pk %}">{{ course_offering.course.title }} ({{ course_offering.course_id }})</a></li>
                        {% empty %}
                        <li class="list-group-item borderless">There is no course</li>
                        {% endfor %}
                    </ul>
                </div>		
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

ITSupportingWebApp/elearning/templates/elearning/course_offering_detail.html
{% extends "elearning/base.html" %}

{% block title %}
    {{ course_offering.title }}
{% endblock  %}

{% block css_extra %}
<style>
    h2{
        color:#1f808c;
    }

    .jumbotron p{
        font-size: 12pt;
    }

    #course_offering-aside-panel .list-group-item {
        font-size: 10pt;
    }

    li.borderless {
        border-top: 0 none;
    }

    .table-borderless > tbody > tr > td,
    .table-borderless > tbody > tr > th,
    .table-borderless > tfoot > tr > td,
    .table-borderless > tfoot > tr > th,
    .table-borderless > thead > tr > td,
    .table-borderless > thead > tr > th {
        border: none;
    } 

    .modal {
        text-align: center;
        padding: 0!important;
    }

    .modal:before {
        content: '';
        display: inline-block;
        height: 100%;
        vertical-align: middle;
        margin-right: -4px;
    }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }

</style>
{% endblock %}

{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="{% url 'home' %}">Home</a></li>
                            <li><a href="{% url 'elearning:course_detail' course_offering.course.pk %}">{{ course_offering.course.title }}</a></li>
                            <li>{{course_offering.offering_id}}</li>
						</ul>
						<h1 class="white-text">{{course_offering.offering_id}}</h1>

					</div>
				</div>
			</div>
{% endblock %}

{% block course %}

    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">Home Page</div>
            <div class="panel-body">
                <div class="jumbotron">
                    <h2>About this course</h2>
                    <br>
                    <div class="row">
                        <p class="col-md-3"><strong>Title:</strong></p>
                        <p class="col-md-9">{{ course.title }}</p>
                    </div>
                    <div class="row">
                        <p class="col-md-3"><strong>Level:</strong></p>
                        <p class="col-md-9">Undergraduate</p>
                    </div>
                    <div class="row">
                        <p class="col-md-3"><strong>Credits:</strong></p>
                        <p class="col-md-9">{{ course.num_credits }}</p>
                    </div>
                    <div class="row">
                        <p class="col-md-3"><strong>Overview:</strong></p>
                        <p class="col-md-9">{{ course.overview }}</p>
                    </div>
                </div>
    
        
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title" style="color:#1f808c;font-size:16px;" data-toggle="collapse" data-target="#collapse1">
                                Course content<span class="glyphicon glyphicon-plus pull-right"></span>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            {% if contents %}
                            <ul class="list-group">
                            {% for content in contents %}
                                <a href="{% url 'elearning:content_detail' course_offering.pk content.pk %}"><li class="list-group-item">{{ content.title }}</li></a>
                            {% endfor %}
                            </ul>
                            {% else %}
                            <div class="panel-body">
                                There is no content available
                            </div>
                            {% endif %}    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock  %}

{% block paging %}

{% endblock %}

{% block aside %}
    
    <div class="widget">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading" data-toggle="collapse" data-target="#course_offering-aside-panel">
                    <h4 class="panel-title" style="color:#1f808c;font-size:14px;">
                        <span class="caret"></span>
                        {{ course_offering.course.title }}<span class="glyphicon glyphicon-home pull-right"></span><br>({{ course_offering.offering_id }})
                    </h4>
                </div>
                <div id="course_offering-aside-panel" class="panel-collapse collapse">
                    <ul class="list-group">
                        <li class="list-group-item borderless"><a href="{% url 'elearning:course_offering_detail' course_offering.pk %}">Home page</a></li>
                        
                        <li class="list-group-item borderless"><a href="{% url 'elearning:owner_contact' course_offering.pk %}">Staff contacts</a></li>
                        <li class="list-group-item borderless"><a href="{% url 'elearning:discussion' course_offering.pk %}">Discussions</a></li>
                        <li class="list-group-item borderless"><a href="{% url 'elearning:assignments' course_offering.pk %}">Assignments</a></li>
                        {% if request.user.profile.role == 'student' %}
                        <li class="list-group-item"><a href="{% url 'elearning:grade' course_offering.pk request.user.username %}">My grades</a></li>
                        {% elif request.user.profile.role == 'professor' %}
                        <li class="list-group-item borderless"><a href="{% url 'elearning:add_content' course_offering.pk %}">Add Content</a></li>
                        <li class="list-group-item"><a href="{% url 'elearning:grade_list' course_offering.pk %}">Grades</a></li>
                        {% endif %}
                    </ul>
                </div>		
            </div>
        </div>
    </div>

{% endblock %}