ITSupportingWebApp/ITSupportingWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from elearning.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('about',about, name='about'),
    path('account/',include('account.urls')),
    path('forum/',include('forum.urls')),
    path('elearning/',include('elearning.urls')),
    path('event/',include('event.urls')),
    path('froala/',include('froala_editor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITSupportingWebApp/event/urls.py
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    path('',views.event_list,name='event_list'),
    path('create_event/',views.create_event,name='create_event'),
    path('<int:pk>/',views.event_detail,name='event_detail'),
    path('<int:pk>/edit',views.edit_event,name='edit_event'),
    path('<int:pk>/delete',views.delete_event,name='delete_event'),
    path('<int:pk>/join',views.join_event,name='join_event'),
    path('notis/',views.notis_json, name='notis.json'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

ITSupportingWebApp/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('',views.category_list,name='category'),
    path('posts/',views.search_post,name='search_post'),
    path('<str:category_slug>/post/',views.post_list,name='post_list'),
    path('<str:category_slug>/post/<str:post_id>',views.post_detail,name='post_detail'),
    path('create_post/',views.create_post,name='create_post'),
    path('<str:category_slug>/post/<str:post_id>/delete',views.delete_post,name='delete_post'),
    path('<str:category_slug>/post/<str:post_id>/<str:comment_id>/delete',views.delete_comment,name='delete_comment'),
    path('<str:category_slug>/post/<str:post_id>/edit',views.edit_post,name='edit_post'),
    path('<str:category_slug>/post/<str:post_id>/like_post',views.like_post,name='like_post'),
    path('<str:category_slug>/post/<str:post_id>/like_comment',views.like_comment,name='like_comment'),
]

ITSupportingWebApp/forum/models.py
from djongo import models
from django.utils import timezone
from django.contrib.auth.models import User
from froala_editor.fields import FroalaField
from django.urls import reverse
import uuid
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(primary_key=True, unique=True)
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                        .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
        ('pending','Pending'),
        ('reject','Reject'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='posts')
    body = FroalaField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    views = models.IntegerField(default=0)
    like = models.ManyToManyField(User,related_name='liked_posts',blank=True)
    dislike = models.ManyToManyField(User,related_name='disliked_posts',blank=True)

    class meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('forum:post_detail',
                        args=[str(self.category.slug),str(self.id)])

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    like = models.ManyToManyField(User,related_name='liked_comments',blank=True)
    dislike = models.ManyToManyField(User,related_name='disliked_comments',blank=True)
    
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {} at {}'.format(self.author,self.post,self.created)

ITSupportingWebApp/forum/forms.py
from .models import Post, Comment, Category
from django.forms import ModelForm

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','category','body']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']

ITSupportingWebApp/forum/views.py
from django.shortcuts import render, get_object_or_404,HttpResponse, redirect
from .models import Post,Comment,Category
from .forms import PostForm,CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Permission
from django.utils import timesince
import json
from django.core.paginator import Paginator

# Create your views here.

def get_user(request):
    user = User.objects.get(username=request.user.username)
    return user

def category_list(request):
    categories = Category.objects.all()
    category_list = []
    all_posts = Post.published.order_by('-publish')[:3]
    for category in categories:
        try:
            latest_post = category.posts.filter(status='published').latest('publish')
            id = latest_post.id
            title = latest_post.title
            published = latest_post.publish
            author = latest_post.author
            category_list.append({
                'name': category.name,
                'slug': category.slug,
                'total_posts': category.posts.count(),
                'latest_post_id': id,
                'latest_post_title':title,
                'latest_post_published':published,
                'author': author,
            })
        except:
            category_list.append({
                'name': category.name,
                'slug': category.slug,
                'total_posts': 0,
            })
    return render(request,'forum/category.html',{'categories':category_list,'all_posts':all_posts})

def post_list(request, category_slug):
    categories = Category.objects.all()
    category = Category.objects.get(slug=category_slug)
    all_posts = category.posts.filter(status='published').order_by('-publish')
    for post in all_posts:
        post.num_comment = post.comments.count()
        comments = Comment.objects.filter(post=post)
        if comments:
            latest_comment = comments.latest('created')
            post.latest_comment = latest_comment.body
            post.latest_comment_author = latest_comment.author
            post.latest_comment_created = latest_comment.created

    paginator = Paginator(all_posts, 10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request,'forum/post_list.html',{'ctg':category,
                                            'categories':categories, 
                                            'all_posts':all_posts,
                                            'posts':posts, 
                                            'section':'post_list'})

def search_post(request):
    search = request.GET.get('search')
    categories = Category.objects.all()
    all_posts = Post.objects.filter(status='published').order_by('-publish')
    search_posts = Post.objects.filter(status='published',title__icontains=search) or Post.objects.filter(status='published',body__icontains=search)
    search_posts = search_posts.order_by('-publish')
    for post in search_posts:
        post.num_comment = post.comments.count()
        comments = Comment.objects.filter(post=post)
        if comments:
            latest_comment = comments.latest('created')
            post.latest_comment = latest_comment.body
            post.latest_comment_author = latest_comment.author
            post.latest_comment_created = latest_comment.created

    paginator = Paginator(search_posts, 10)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request,'forum/search_post_list.html',{'search':search,
                                            'categories':categories,
                                            'all_posts':all_posts,
                                            'posts':posts, 
                                            'section':'post_list'})

def post_detail(request, category_slug, post_id):
    form = PostForm()
    comment_form = CommentForm()

    category = Category.objects.get(slug=category_slug)
    posts = category.posts.filter(status='published')
    categories = Category.objects.all()
    post = get_object_or_404(Post, id=post_id, 
                                status="published",)
    comments = post.comments.all()

    if request.method=="GET":
        post.views = post.views + 1
        post.save()
    
    if request.user.is_authenticated:
        if request.user in post.like.all():
            post.is_liked = True
        for comment in comments:
            if request.user in comment.like.all():
                comment.is_liked = True
        if request.method=="POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = post
                new_comment.author = get_user(request)
                new_comment.save()
            return redirect('forum:post_detail',category_slug,post_id)
        
    return render(request, 'forum/post_detail.html',{'ctg':category,
                                            'categories':categories,
                                            'posts':posts,
                                            'post':post,
                                            'comments':comments,
                                            'comment_form':comment_form,
                                            'form':form})

@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = get_user(request)
            if new_post.author.is_staff | new_post.author.has_perm('forum.add_post'):
                new_post.status = "published"
                new_post.save()
                category_slug = new_post.category.slug
                return redirect('forum:post_detail', category_slug=category_slug, post_id=str(new_post.id))
            else:
                new_post.status = "pending"
                new_post.save()
                return redirect('forum:category')
    else:
        form = PostForm()
    return render(request, 'forum/create_post.html',{'form':form})

@login_required
def delete_post(request, category_slug, post_id):
    post = get_object_or_404(Post,id=post_id)
    if post.author.username == get_user(request).username:
        post.delete()
    else:
        return "Do not have permission"
    return redirect('forum:post_list',category_slug=category_slug)

@login_required
def delete_comment(request, category_slug, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author.username == get_user(request).username:
        comment.delete()
    else:
        return "Do not have permission"
    return redirect('forum:post_detail',category_slug=category_slug,post_id=str(post_id))

@login_required
def edit_post(request, category_slug, post_id):
    category = Category.objects.get(slug=category_slug)
    post = get_object_or_404(Post,id=post_id)
    form = PostForm()
    if post.author.username == get_user(request).username:
        if request.method == 'POST':
            post.body = request.POST.get('body')
            post.save()
            return redirect('forum:post_detail',category_slug=category_slug,post_id=str(post_id))
    else:
        return "Do not have permission"
    return render(request,'forum/edit_post.html',{'ctg':category,'post':post,'form':form})

@login_required
def like_post(request, category_slug, post_id):
    if request.is_ajax():
        json_data = request.read()
        json_data = json.loads(json_data)
        username = json_data['username']
        post_id = json_data['post_id']
        user = User.objects.get(username=username)
        post = Post.objects.get(id=post_id)
        if request.method == "POST":
            post.like.add(user)
            liked_users = post.like.all()
        elif request.method == "DELETE":
            post.like.remove(user)
            liked_users = post.like.all()
        data = []
        for liked_user in liked_users:
            data.append({
                'name': liked_user.username,
            })
        print(data)
        return HttpResponse(json.dumps(data),
                            content_type='application/json')

@login_required
def like_comment(request, category_slug, post_id):
    if request.is_ajax():
        json_data = request.read()
        json_data = json.loads(json_data)
        username = json_data['username']
        comment_id = json_data['comment_id']
        user = User.objects.get(username=username)
        comment = Comment.objects.get(id=comment_id)
        
        if request.method == "POST":
            comment.like.add(user)    
        elif request.method == "DELETE":
            comment.like.remove(user)

        liked_users = comment.like.all()
        data = []
        for liked_user in liked_users:
            data.append({
                'name': liked_user.username,
            })
        print(data)
        return HttpResponse(json.dumps(data),
                            content_type='application/json')

ITSupportingWebApp/forum/templates/forum/base.html
{% extends "base.html" %}

{% load static %}

{% block css_extra %}
<style>

.panel-body strong, .panel-body .fa{
    color:rgb(8, 73, 126);
}

.panel-body .fa{
    display: inline-block;
    width: 100%;
}
.panel-body{
    margin-left: 20px;
    margin-right: 20px;
}

.date {
	font-size:12px;
	color:#374050;
}

.panel-body hr{
    height:1px; 
    color:rgb(8, 73, 126); 
    background-color:rgb(8, 73, 126);
}

.header-item{
    background-color:#ffcc99;
}

</style>

{% endblock %}

{% block transparent-nav %}

{% endblock %}

{% block home %}
    <div class="hero-area section">

			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url({% static 'account/assets/img/background.jpg' %})"></div>
			<!-- /Backgound Image -->
			{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="{% url 'home' %}">Home</a></li>
							<li><a href="{% url 'forum:category' %}">Forum</a></li>
						</ul>
						<h1 class="white-text">Forum Page</h1>

					</div>
				</div>
			</div>
			{% endblock %}
	</div>
{% endblock %}

{% block content %}
    <div id="blog" class="section">

		<!-- container -->
		<div class="container">

		<!-- row -->
			<div class="row">
			<!-- main blog -->
				<div id="main" class="col-md-9">
                    
					{% block post %}
				    <!-- row -->
				    <div class="row">
                    </div>    
					<!-- /row -->
                    {% endblock %}

					<!-- row -->
					<div class="row">
                        {% block paging %}
						<!-- pagination -->
						<div class="col-md-12">
							<div class="post-pagination">
								<a href="#" class="pagination-back pull-left">Back</a>
								<ul class="pages">
									<li class="active">1</li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">4</a></li>
								</ul>
								<a href="#" class="pagination-next pull-right">Next</a>
							</div>
						</div>
						<!-- pagination -->
                        {% endblock %}
					</div>
					<!-- /row -->
		        </div>
                <!-- /main blog -->

				{% block aside %}
                <!-- aside blog -->
				<div id="aside" class="col-md-3">

					<!-- search widget -->
					<div class="widget search-widget">
						<form action="{% url 'forum:search_post' %}" method="GET">
							<input class="input" type="text" name="search" placeholder="Search Posts">
							<button><i class="fa fa-search"></i></button>
						</form>
					</div>
					<!-- /search widget -->

					<!-- category widget -->
					<div class="widget category-widget">
						<h3>Categories</h3>
						{% for category in categories %}
						<a class="category" href="{% url 'forum:post_list' category.slug %}">{{ category.name }} 
						<span class="pull-right">
							{% if category.total_posts %}
								{{ category.total_posts }}
							{% else %}
								{% with category.posts.count as total_posts %}
                                	{{total_posts}}
                            	{% endwith %}
							{% endif %}
						</span></a>
						{% endfor %}
					</div>
					<!-- /category widget -->

					<!-- posts widget -->
					<div class="widget posts-widget">
						<h3>Latest {% if ctg.name %}{{ctg.name}}{% endif %} Posts</h3>
						{% for post in all_posts %}
						{% if forloop.counter <= 3 %}
						<!-- single posts -->
						<div class="single-post">
							<a class="single-post-img" href="#">
								<img src="{% static 'img/blog01.jpg' %}" alt="">
							</a>
							<a href="{{post.get_absolute_url}}">{{ post.title }}</a>
							<p><small>By {{post.author}} .{{post.publish}}</small></p>
						</div>
						<!-- /single posts -->
						{% endif %}
						{% empty %}
						<p>There is no post</p>
						{% endfor %}

					</div>
					<!-- /posts widget -->

					<!-- tags widget -->
					{% comment %} <div class="widget tags-widget">
						<h3>Tags</h3>
						<a class="tag" href="#">Web</a>
						<a class="tag" href="#">Photography</a>
						<a class="tag" href="#">Css</a>
						<a class="tag" href="#">Responsive</a>
						<a class="tag" href="#">Wordpress</a>
						<a class="tag" href="#">Html</a>
						<a class="tag" href="#">Website</a>
						<a class="tag" href="#">Business</a>
					</div> {% endcomment %}
					<!-- /tags widget -->

				</div>
				<!-- /aside blog -->
				{% endblock %}
				
			</div>
			<!-- row -->

		</div>
		<!-- container -->

	</div>
	<!-- /Blog -->
{% endblock %}

ITSupportingWebApp/forum/templates/forum/category.html
{% extends "forum/base.html" %}

{% block title %}
    Forum
{% endblock  %}

{% block post %}
<div class="panel panel-default">
    <div class="panel-heading">Categories</div>

    <div class="panel-body">
        <div class="row">
            <a href="{% url 'forum:create_post' %}" class="btn btn-success pull-right">Create Post</a>
        </div>
        <br>

        <div class="row">
            <ol>
                {% for category in categories %}
                <li>
                    <div class="row">
                        <div class="col-md-1"><i class="fa fa-comments fa-lg text-center"></i></div>
                        <div class="col-md-6">
                            <a href="{% url 'forum:post_list' category.slug %}">
                                <p><strong>{{ category.name }}</strong></p>
                            </a>
                            <p>Post:
                                {{ category.total_posts }}
                            </p>
                        </div>
                        <div class="col-md-5">
                        <div style="background:#d7edfc; padding:3px 10px">
                            {% if category.latest_post_title %}
                            <p>Latest: <a href="{% url 'forum:post_detail' category.slug category.latest_post_id %}"><span>{{ category.latest_post_title|truncatewords:5 }}</span></a>
                            <span>by {{ category.author }}</span></p>
                            <p class="date">{{ category.latest_post_published|timesince }} ago</p>
                            {% else %}
                            <p>There is no post in this category</p>
                            {% endif %}
                        </div>
                        </div>
                    </div>
                </li>
                <hr>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock  %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/forum/templates/forum/create_post.html
{% extends "forum/base.html" %}

{% block title %}
    Create Post
{% endblock  %}

{% block post %}
    <h1>Create your Post</h1>
    <form action="{% url 'forum:create_post' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="main-button icon-button">Post</button>
    </form>
{% endblock %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/forum/templates/forum/edit_post.html
{% extends "forum/post_detail.html" %}

{% block title %}
    Edit Post
{% endblock  %}

{% block post %}
    <h1>Edit your Post</h1>
    <form method="POST">
        {% csrf_token %}
        <textarea id="id_body" name="body" required>
            {% autoescape off %}
                {{ post.body }}
            {% endautoescape %}
        </textarea>
        <br>       
        <button class="main-button icon-button">Edit</button>
    </form>

    <script>
        $(function() {
            $('#id_body').froalaEditor({
                "inlineMode": false, 
                "imageUploadURL": "/froala/image_upload/", 
                "imageUploadParams": {"csrfmiddlewaretoken": getCookie("csrftoken")}, 
                "fileUploadURL": "/froala/file_upload/", 
                "fileUploadParams": {"csrfmiddlewaretoken": getCookie("csrftoken")},
            })
        });
    </script>
{% endblock %}

{% block paging %}

{% endblock %}

ITSupportingWebApp/forum/templates/forum/post_detail.html
{% extends "forum/base.html" %}

{% load widget_tweaks %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block home-wrapper %}
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><a href="index.html">Home</a></li>
							<li><a href="{% url 'forum:category' %}">Forum</a></li>
							<li><a href="{% url 'forum:post_list' ctg.slug %}">{{ ctg.name }}</a></li>
                            <li>{{post.title}}</li>
						</ul>
						<h1 class="white-text">{{post.title}}</h1>
                        <ul class="blog-post-meta">
							<li class="blog-meta-author">By : <a href="#">{{post.author}}</a></li>
							<li>{{post.created}}</li>
							<li class="blog-meta-comments"><a href="#"><i class="fa fa-comments"></i> 
                                {% with comments.count as total_comments %}
                                	{{total_comments}}
                                {% endwith %}
                            </a></li>
						</ul>
					</div>
				</div>
			</div>
{% endblock %}

{% block post %}
	<!-- blog post -->
	<div class="blog-post fr-view">
		{% autoescape off %}
            {{ post.body }}
        {% endautoescape %}
	</div>
	<a href="#" class="fa fa-thumbs-up post-liked" {% if post.is_liked %} style="color:#007acc" {% endif %}><span> 
	{% with post.like.count as total_liked %}
		{{total_liked}}
	{% endwith %}
	</span></a>
    {% if request.user.username == post.author.username %}
        <a href="{% url 'forum:delete_post' ctg.slug post.id %}" class="btn btn-success fa fa-trash pull-right"></a>
		<a href="{% url 'forum:edit_post' ctg.slug post.id %}" class="btn btn-success fa fa-edit pull-right"></a>	
    {% endif %}
    <hr>
	<!-- /blog post -->

	<!-- blog comments -->
	<div class="blog-comments">
		<h3>
		{% with comments.count as total_comments %}
			{{total_comments}} Comments
		{% endwith %}
		</h3>

        {% for comment in comments %}
		<!-- single comment -->
		<div class="media">
			<div class="media-left">
				{% if comment.author.profile.avatar != "" %}
				<img src="{{ MEDIA_URL }}{{ comment.author.profile.avatar }}" />
				{% else %}
				<img src="https://epicattorneymarketing.com/wp-content/uploads/2016/07/Headshot-Placeholder-1.png" />
				{% endif %}
			</div>
			<div class="media-body">
				<h4 class="media-heading">{{comment.author}}
                    {% if request.user.username == comment.author.username %}
                        <a href="{% url 'forum:delete_comment' ctg.slug post.id comment.id %}" class="btn pull-right"><span class="glyphicon glyphicon-remove"></span></a>
                    {% endif %}
                </h4>
				<p>{{comment.body}}</p>
				<div class="date-reply"><span>{{comment.created}}</span></div>
				<a href="#" id="{{comment.id}}" data-is-liked="{{comment.is_liked}}" class="fa fa-thumbs-up comment-liked" {% if comment.is_liked %} style="color:#007acc" {% endif %}><span> 
					{% with comment.like.count as total_liked %}
						{{total_liked}}
					{% endwith %}
				</span></a>
			</div>
		</div>
		<!-- /single comment -->
        {% empty %}
        <p>There are no comments yet.</p>
        {% endfor %}

		<!-- blog reply form -->
        {% if request.user.is_authenticated %}
		<div class="blog-reply-form">
	    	<h3>Leave Comment</h3>
			<form action="{{post.get_absolute_url}}" method="post">
				{% csrf_token %}
                {% render_field comment_form.body class="input" name="message" placeholder="Enter your Message" %}
				<button class="main-button icon-button">Submit</button>
			</form>
		</div>
        {% else %}
        <button class="main-button icon-button"><a href="{% url 'login' %}">Login to comment</a></button>
		{% endif %}
        <!-- /blog reply form -->

	</div>
	<!-- /blog comments -->
	<script>
		$('.input').text('');
	</script>

	<!-- Like post -->
	<script>
	if ('{{request.user.is_authenticated}}'=='True'){
		var post_is_liked = '{{post.is_liked}}';

		$('.post-liked').on('click',function(){
			var username = '{{request.user.username}}';
			var post_id = '{{post.id}}';
			var data = {
				username: username,
				post_id: post_id,
			};
			var method = '';
			
			if ( post_is_liked =='True'){
				$('.post-liked').css("color","initial");
				method = 'DELETE';
				post_is_liked = 'False';
			}
			else{
				$('.post-liked').css("color","#007acc");
				method = 'POST';
				post_is_liked = 'True';
			}

			$.ajax({
				method: method,
     			url: "{% url 'forum:like_post' ctg.slug post.id %}",
				headers: {'X-CSRFToken':'{{csrf_token}}'},
        		dataType: 'JSON',
                data: JSON.stringify(data),
				success: function(data){
					var user = "";
					var total_liked = 0;
					$.each(data, function(i,value){
						user = user + value['name'] + ", ";
						total_liked = total_liked + 1;
					})
					$('.post-liked').text(' ' + total_liked);
					alert(user);
				}
      		})
		});
	}
	</script>
	<!-- End Like post -->

	<!-- Like comment -->
	<script>
	if ('{{request.user.is_authenticated}}'=='True'){

		$('.comment-liked').on('click',function(){
			var comment_is_liked = $(this).data('is-liked');
			var username = '{{request.user.username}}';
			var comment_id = $(this).attr('id');
			var data = {
				username: username,
				comment_id: comment_id,
			};
			var method = '';
			
			if ( comment_is_liked =='True'){
				$(this).css("color","initial");
				method = 'DELETE';
				$(this).data('is-liked','False');
			}
			else{
				$(this).css("color","#007acc");
				method = 'POST';
				$(this).data('is-liked','True');
			}

			$.ajax({
				method: method,
     			url: "{% url 'forum:like_comment' ctg.slug post.id %}",
				headers: {'X-CSRFToken':'{{csrf_token}}'},
        		dataType: 'JSON',
                data: JSON.stringify(data),
				success: function(data){
					var user = "";
					var total_liked = 0;
					$.each(data, function(i,value){
						user = user + value['name'] + ", ";
						total_liked = total_liked + 1;
					})
					$('#'+comment_id).text(' ' + total_liked);
					alert(user);
				}
      		})
		});
	}
	</script>
	<!-- End Like comment -->

{% endblock %}

{% block paging %}

{% endblock %}